jobs:
  - job: "terraform"
    pool:
      vmImage: ${{ parameters.agentPool }}
    steps:
    # - task: Checkout
    #   displayName: Checkout
    #   uses: actions/checkout@v3

    # - task: Checkout
    #   displayName: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     repository: hmcts/cnp-azuredevops-libraries
    #     path: cnp-azuredevops-libraries

    - task: Setup Script
      displayName: Setup Script
      script: |
        chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
      
    - task: Setup Script
      displayName: Setup Terraform
      script: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
      workingDirectory: ./
      shell: bash

    # - task: Terraform Init
    #   displayName: Terraform Init
    #   run: terraform init
    #   working-directory: example

    # - task: Terraform validate
    #   displayName: Terraform validate
    #   run: terraform validate
    #   working-directory: example

    # - task: Terraform format
    # - displayName: Terraform format
    #   run: terraform fmt -check