jobs:
- job: "terraform"
  agentPool: 'ubuntu-18.04'
  steps:
    - displayName: Checkout
      uses: actions/checkout@v3

    - displayName: Checkout
      uses: actions/checkout@v3
      with:
        repository: hmcts/cnp-azuredevops-libraries
        path: cnp-azuredevops-libraries

    - displayName: Setup Script
      run: |
        chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
    - displayName: Setup Terraform
      run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
      working-directory: ./
      shell: bash

    - displayName: Terraform Init
      run: terraform init
      working-directory: example

    - displayName: Terraform validate
      run: terraform validate
      working-directory: example

    - displayName: Terraform format
      run: terraform fmt -check