trigger:
  batch: true
  branches:
    include:
      - master

variables:
  terraformVersion: 0.12.23
  agentPool: 'ubuntu-18.04'

stages:
  - stage: Plan_phase
    displayName: "Terraform Plan"
    jobs:
      - template: pipeline-templates/terraform-plan.yaml
        parameters:
          zone: 'sandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
          backendServiceArm: 'dts-cftsbox-intsvc'
          backendAzureRmResourceGroupName: 'core-infra-intsvc-rg'
          backendAzureRmStorageAccountName: 'cftsboxintsvc'

  - stage: Sandbox_Apply
    dependsOn: Plan_phase
    displayName: "Sandbox Apply"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipeline-templates/terraform-apply.yaml
        parameters:
          zone: 'sandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
          backendServiceArm: 'dts-cftsbox-intsvc'
          backendAzureRmResourceGroupName: 'core-infra-intsvc-rg'
          backendAzureRmStorageAccountName: 'cftsboxintsvc'

