trigger:
  batch: true
  branches:
    include:
      - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: timeoutInMinutes
    value: "60"
  - name: agentPool
    value: "ubuntu-latest" 
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: "cft-platform"
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  
parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

  - name: environment_components
    type: object
    default:
    - deployment: demo
      environment: demo
      component: demo
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: dev
      environment: preview
      component: dev
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: ithc
      environment: ithc
      component: ithc
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: test
      environment: perftest
      component: test
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: privatelink
      environment: privatelink
      component: privatelink
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: prod
      environment: prod
      component: prod
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck
    - deployment: sandbox
      environment: sbox
      component: sandbox
      serviceConnection: dts-cftsbox-intsvc
      dependsOn:
        - Precheck
    - deployment: staging
      environment: staging
      component: staging
      serviceConnection: dts-cftptl-intsvc
      dependsOn:
        - Precheck

stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFTAPPS-SBOX'

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              product: ${{ variables.product }}
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              component: ${{ deployment.component }}
              serviceConnection: ${{ deployment.serviceConnection }}
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
