trigger:
  batch: true
  branches:
    include:
      - master

variables:
  terraformVersion: 0.12.23
  poolName: privatedns-prod
  agentPool: 'ubuntu-18.04'

stages:
  - stage: Plan_phase
    displayName: "Terraform Plan"
    jobs:
      - template: pipeline-templates/terraform-plan.yaml
        parameters:
          zone: 'sandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
          backendServiceArm: 'dts-cftsbox-intsvc'
          backendAzureRmResourceGroupName: 'core-infra-intsvc-rg'
          backendAzureRmStorageAccountName: 'cftsboxintsvc'

      - job: Archive
        pool:
          name: ${{ variables.poolName }}
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'

  - stage: Sandbox_Apply
    dependsOn: Plan_phase
    displayName: "Sandbox Apply"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipeline-templates/terraform-apply.yaml
        parameters:
          zone: 'sandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
          backendServiceArm: 'dts-cftsbox-intsvc'
          backendAzureRmResourceGroupName: 'core-infra-intsvc-rg'
          backendAzureRmStorageAccountName: 'cftsboxintsvc'

