name: "platform.hmcts.net"
vnet_links:
  - link_name: "core-infra-vnet-prod-internal"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-prod/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-prod"
  - link_name: "core-infra-vnet-idam-prod"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-idam-prod/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-idam-prod"
  - link_name: "core-infra-vnet-idam-prod2"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-idam-prod2/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-idam-prod2"
  - link_name: "mgmt-infra-platform"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/mgmt-infra-prod/providers/Microsoft.Network/virtualNetworks/mgmt-infra-prod"
  # sandbox
  - link_name: "core-infra-vnet-sandbox-idam-internal"
    vnet_id: "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/core-infra-sandbox/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-sandbox"
  - link_name: "core-infra-vnet-idam-sandbox-idam-internal"
    vnet_id: "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/core-infra-idam-sandbox/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-idam-sandbox"
  - link_name: "mgmt-infra-sandbox-idam-internal"
    vnet_id: "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/mgmt-infra-sandbox/providers/Microsoft.Network/virtualNetworks/mgmt-infra-sandbox"
A: []
cname: []
