name: "prod.internal.hmcts.net"
vnet_links:
  - link_name: "private-dns-resolver-uksouth-vnet-prod-int"
    vnet_id: "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/private-dns-resolver-uksouth-prod-int/providers/Microsoft.Network/virtualNetworks/private-dns-resolver-uksouth-vnet-prod-int"
  - link_name: "core-aad-domain-services-mgmt-vnet"
    vnet_id: "/subscriptions/2b1afc19-5ca9-4796-a56f-574a58670244/resourceGroups/core-aad-domain-services-mgmt-rg/providers/Microsoft.Network/virtualNetworks/core-aad-domain-services-mgmt-vnet"
  - link_name: "soc-prod-vnet"
    vnet_id: "/subscriptions/8ae5b3b6-0b12-4888-b894-4cec33c92292/resourceGroups/soc-core-infra-prod-rg/providers/Microsoft.Network/virtualNetworks/soc-prod-vnet"
A:
  - name: familyman
    record:
      - 10.23.15.11
    ttl: 300
  - name: data-analytics
    record:
      - 10.23.4.132
    ttl: 300
  - name: xhibitthin
    record:
      - 10.23.1.253
    ttl: 300
  - name: sdae-promon
    record:
      - 10.23.4.137
    ttl: 300
  - name: sdae-siem
    record:
      - 10.23.4.138
    ttl: 300
  - name: pih4171sec001
    record:
      - 10.23.3.164
    ttl: 300
  - name: pih4171sec002
    record:
      - 10.23.3.165
    ttl: 300
  - name: pih4171sec003
    record:
      - 10.23.3.166
    ttl: 300
  - name: pih4171sec004
    record:
      - 10.23.3.167
    ttl: 300
  - name: pih4172sec001
    record:
      - 10.25.3.164
    ttl: 300
  - name: pih4172sec002
    record:
      - 10.25.3.165
    ttl: 300
  - name: pih4172sec003
    record:
      - 10.25.3.166
    ttl: 300
  - name: pih4172sec004
    record:
      - 10.25.3.167
    ttl: 300
  - name: pihw4172rdp001
    record:
      - 10.25.3.132
    ttl: 300
  - name: pihw4172rdp021
    record:
      - 10.25.5.132
    ttl: 300
  - name: pihw4171rdp001
    record:
      - 10.23.3.132
    ttl: 300
  - name: pihw4171rdp021
    record:
      - 10.23.5.132
    ttl: 300
  - name: pihw4172dfs001
    record:
      - 10.25.3.150
    ttl: 300
  - name: pihw4171dfs001
    record:
      - 10.23.3.150
    ttl: 300
  - name: martha
    record:
      - 10.24.245.12
    ttl: 300
  - name: tec
    record:
      - 10.23.15.139
    ttl: 300
  - name: libra-preview
    record:
      - 10.23.15.90
    ttl: 300
  - name: libra-gateway
    record:
      - 10.23.15.71
    ttl: 300
  - name: libra
    record:
      - 10.23.15.89
    ttl: 300
  - name: libra-gob
    record:
      - 10.23.15.68
    ttl: 300
  - name: libra-cpp-gob-gateway
    record:
      - 10.23.15.72
    ttl: 300
  - name: libra-onpremise-gob-gateway
    record:
      - 10.23.15.79
    ttl: 300
  - name: libra-dmu
    record:
      - 10.23.15.91
    ttl: 300
  - name: libra-appreg
    record:
      - 10.23.15.92
    ttl: 300
  - name: libra-selfservice
    record:
      - 10.23.15.93
    ttl: 300
  - name: libra-docportal
    record:
      - 10.23.15.94
    ttl: 300
  - name: libra-proving
    record:
      - 10.23.15.73
    ttl: 300
  - name: libra-sdrs-gateway
    record:
      - 10.23.15.85
    ttl: 300
  - name: libra-crimeportal-gateway
    record:
      - 10.23.15.86
    ttl: 300
  - name: libra-mis
    record:
      - 10.23.15.74
    ttl: 300
  - name: gaps2
    record:
      - 10.23.15.107
    ttl: 300
cname: []
