name: "prod.int.hmcts.net"
vnet_links:
  - link_name: "core-aad-domain-services-mgmt-vnet"
    vnet_id: "/subscriptions/2b1afc19-5ca9-4796-a56f-574a58670244/resourceGroups/core-aad-domain-services-mgmt-rg/providers/Microsoft.Network/virtualNetworks/core-aad-domain-services-mgmt-vnet"
  - link_name: "prod.int.hmcts.net-vnet-nle-ext-01"
    vnet_id: "/subscriptions/17390ec1-5a5e-4a20-afb3-38d8d726ae45/resourceGroups/InternalSpoke-rg/providers/Microsoft.Network/virtualNetworks/vnet-prod-int-01"
    registration_enabled: true
A:
  - name: EUCW4171PRN004
    record:
    - 10.172.69.16
    ttl: 300
  - name: EUCW4171PRN001
    record:
    - 10.172.69.19
    ttl: 300
  - name: EUCW4171PRN003
    record:
    - 10.172.69.18
    ttl: 300
  - name: EUCW4171PRN002
    record:
    - 10.172.69.17
    ttl: 300
  - name: EUCW4172PRN004
    record:
    - 10.171.69.16
    ttl: 300
  - name: EUCW4172PRN001
    record:
    - 10.171.69.17
    ttl: 300
  - name: EUCW4172PRN002
    record:
    - 10.171.69.19
    ttl: 300
  - name: EUCW4172PRN003
    record:
    - 10.171.69.18
    ttl: 300
  - name: EUCW4171PRN005
    record:
    - 10.172.69.13
    ttl: 300
  - name: EUCW4172PRN005
    record:
    - 10.171.69.13
    ttl: 300
cname:
  - name: PRN0000
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0006A
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0023
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0027
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0040
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0041
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0049
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0051
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0053
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0069
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0078
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0083
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0095
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0098
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0099
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0101
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0102
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0104
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0105
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0106
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0107
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0108
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0109
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0119
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0123
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0136
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0139
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0140
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0143
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0144
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0150
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0158
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0159
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0163
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0166
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0169
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0172
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0174
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0175
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0177
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0224
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0236
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0246
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0253
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0256
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0260
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0281
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0291
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0297
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0323
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0327
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0328
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0544
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0557
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0559
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0561
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0564
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0565
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0567
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0571
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0577
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0592
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0698
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0709
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0713
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0719
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0724
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0731
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0733
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0753
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0761
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0772
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0773
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0781
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0782
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0786
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0787
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0789
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0791
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0793
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0794
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0823
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0831
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN0939
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1098
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1107
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1149
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1154
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1226
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1247
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1249
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1274
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1275
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1288
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1302
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1307
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1393
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1396
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1400
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1403
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1409
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1418
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1425
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1428
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1429
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1444
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1450
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1452
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1462
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1463
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1481
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1512
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1516
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1551
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1556
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1559
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1565
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1567
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1569
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1579
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1604
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1628
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1637
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1658
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1676
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1729
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1746
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN1966
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN2097
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN2664
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN2991
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3383
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3385
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3395
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3585A
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3807
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3927
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3962
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN3965
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN4225
    record: EUCW4172PRN004.prod.int.hmcts.net
    ttl: 300
  - name: PRN4260
    record: EUCW4171PRN004.prod.int.hmcts.net
    ttl: 300
