name: "prod.platform.hmcts.net"
vnet_links:
  - link_name: "core-infra-vnet-prod-internal"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-prod/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-prod"
  - link_name: "core-infra-vnet-idam-prod"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-idam-prod/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-idam-prod"
  - link_name: "core-infra-vnet-idam-prod2"
    vnet_id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/core-infra-idam-prod2/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-idam-prod2"
  - link_name: "pet-prod-vnet"
    vnet_id: "/subscriptions/58a2ce36-4e09-467b-8330-d164aa559c68/resourceGroups/pet_prod_network_resource_group/providers/Microsoft.Network/virtualNetworks/pet_prod_network"
  # sandbox
  - link_name: "core-infra-vnet-mgmt"
    vnet_id: "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/rg-mgmt/providers/Microsoft.Network/virtualNetworks/core-infra-vnet-mgmt"
  - link_name: "vpn"
    vnet_id: "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/mgmt-vpn-2-mgmt/providers/Microsoft.Network/virtualNetworks/mgmt-vpn-2-vnet"
  - link_name: "bastion-prod-vnet"
    vnet_id: "/subscriptions/2b1afc19-5ca9-4796-a56f-574a58670244/resourceGroups/bastion-prod-rg/providers/Microsoft.Network/virtualNetworks/bastion-prod-vnet"
  - link_name: "hmi-sharedinfra-vnet-prod"
    vnet_id: "/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/resourceGroups/hmi-sharedinfra-prod-rg/providers/Microsoft.Network/virtualNetworks/hmi-sharedinfra-vnet-prod"
A: 
  - name: vh-wowza
    record:
    - 10.50.11.21
    ttl: 300

cname: []
